name: unit-tests
on:
  pull_request:
    branches:
      - main
    paths:
      - '**.go'
      - Makefile
      - '**.tpl'
      - go.mod
      - go.sum

jobs:
  unit-tests:
    name: make test
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14'
      - name: make test
        run: make test